
import { SubscriptionPlan, Subscription, Company, License, User, ActivityLog, ConfigSettings, DeviceType, OfflineLicenseRecord, OfflineActivationRequest } from './types';
import {
  ActivationStatusEnum,
  LicenseStatusEnum,
  SubscriptionStatusEnum,
} from './licensingLifecycle';

export const MOCK_DEVICE_TYPES: DeviceType[] = [
  { id: 'dt-1', name: 'Windows', status: 'Active' },
  { id: 'dt-2', name: 'Linux', status: 'Active' },
  { id: 'dt-3', name: 'Android', status: 'Active' },
  { id: 'dt-4', name: 'iOS', status: 'Active' },
  { id: 'dt-5', name: 'RFID', status: 'Active' },
];

export const MOCK_PLANS: SubscriptionPlan[] = [
  {
    id: 'plan-1',
    code: 'M-0001',
    name: 'Trial',
    productType: 'Digital Signage',
    status: 'Active',
    duration: 10,
    mode: 'Periodic',
    totalDeviceLimit: 10,
    deviceLimitLabel: '10 Devices',
    description: 'Designed for evaluation and testing purposes',
    highlights: [
      'Limited validity of 10 days from activation',
      'Supports up to 10 devices',
      'Ideal for new users to explore system features',
      'No renewal or upgrade restrictions (can be upgraded to paid plans)',
    ],
    features: ['Email Support', 'Basic Analytics'],
    price: 0,
    billingLabel: '10 Days',
  },
  {
    id: 'plan-2',
    code: 'M-0002',
    name: 'Standard',
    productType: 'Digital Signage',
    status: 'Active',
    duration: 30,
    mode: 'Periodic',
    totalDeviceLimit: 50,
    deviceLimitLabel: '50 Devices',
    description: 'Suitable for small to medium-sized businesses',
    highlights: [
      'Periodic subscription with full feature access',
      'Supports up to 50 devices',
      'Includes standard support and updates',
      'Renewable upon expiry',
    ],
    features: ['Email Support', 'Basic Analytics'],
    price: 500,
    billingLabel: '30 Days',
  },
  {
    id: 'plan-3',
    code: 'M-0003',
    name: 'Professional',
    productType: 'Digital Signage',
    status: 'Active',
    duration: 365,
    mode: 'Periodic',
    totalDeviceLimit: 100,
    deviceLimitLabel: '100 Devices',
    description: 'Suitable for small to medium-sized businesses',
    highlights: [
      'Annual subscription with full feature access',
      'Supports up to 100 devices',
      'Includes standard support and updates',
      'Renewable upon expiry',
    ],
    features: ['24/7 Support', 'Basic Analytics'],
    price: 500,
    billingLabel: '365 Days (1 Year)',
  },
  {
    id: 'plan-4',
    code: 'M-0004',
    name: 'Enterprise',
    productType: 'Digital Signage',
    status: 'Active',
    duration: 0,
    mode: 'Perpetual',
    totalDeviceLimit: 0,
    deviceLimitLabel: 'Unlimited Devices',
    description: 'Designed for large-scale enterprise deployments',
    highlights: [
      'Lifetime validity with no expiration',
      'Supports unlimited devices',
      'Includes advanced features and priority support',
      'One-time purchase (no renewal required)',
    ],
    features: ['Custom Branding', '24/7 Support', 'Advanced Analytics'],
    price: 5000,
    billingLabel: 'Perpetual (No Expiry)',
  },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'TechCorp Solutions',
    email: 'admin@techcorp.com',
    industry: 'Technology',
    contactPerson: 'John Doe',
    primaryMobile: '+1 555-0101',
    status: 'Active',
    linkedSubscriptions: ['sub-1'],
    linkedLicenses: ['lic-1'],
  },
  {
    id: 'comp-2',
    name: 'Global Finance Inc',
    email: 'it@globalfinance.com',
    industry: 'Finance',
    contactPerson: 'Jane Smith',
    primaryMobile: '+1 555-0202',
    status: 'Active',
    linkedSubscriptions: ['sub-2'],
    linkedLicenses: ['lic-2'],
  },
  {
    id: 'comp-3',
    name: 'Innovate AI',
    email: 'contact@innovate.ai',
    industry: 'Artificial Intelligence',
    contactPerson: 'Alice Johnson',
    primaryMobile: '+1 555-0303',
    status: 'Disabled',
    linkedSubscriptions: ['sub-3'],
    linkedLicenses: ['lic-3'],
  },
  {
    id: 'comp-4',
    name: 'Northwind Display Network',
    email: 'ops@northwinddisplay.com',
    industry: 'Retail',
    contactPerson: 'Riya Sharma',
    primaryMobile: '+1 555-0404',
    status: 'Active',
    linkedSubscriptions: ['sub-4'],
    linkedLicenses: [],
  },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1',
    planId: 'plan-1',
    companyId: 'comp-1',
    status: 'Active',
    workflowStatus: SubscriptionStatusEnum.ACTIVE,
    startDate: '2026-03-01',
    endDate: '2026-03-11',
    requestedAt: '2024-12-25',
    approvedAt: '2024-12-28',
    allocations: [
      { deviceTypeId: 'dt-1', count: 10 },
    ],
  },
  {
    id: 'sub-2',
    planId: 'plan-2',
    companyId: 'comp-2',
    status: 'Pending',
    workflowStatus: SubscriptionStatusEnum.PENDING_APPROVAL,
    startDate: '2025-03-15',
    endDate: '2025-04-15',
    requestedAt: '2025-03-10',
    allocations: [
      { deviceTypeId: 'dt-1', count: 17 },
    ],
  },
  {
    id: 'sub-3',
    planId: 'plan-3',
    companyId: 'comp-3',
    status: 'Expired',
    workflowStatus: SubscriptionStatusEnum.EXPIRED,
    startDate: '2024-06-01',
    endDate: '2024-12-01',
    requestedAt: '2024-05-20',
    approvedAt: '2024-05-25',
    allocations: [
      { deviceTypeId: 'dt-1', count: 50 },
      { deviceTypeId: 'dt-2', count: 50 },
    ],
  },
  {
    id: 'sub-4',
    planId: 'plan-2',
    companyId: 'comp-4',
    status: 'Active',
    workflowStatus: SubscriptionStatusEnum.ACTIVE,
    startDate: '2026-03-20',
    endDate: '2026-04-19',
    requestedAt: '2026-03-18',
    approvedAt: '2026-03-19',
    allocations: [
      { deviceTypeId: 'dt-1', count: 40 },
      { deviceTypeId: 'dt-2', count: 10 },
    ],
  },
];

export const MOCK_LICENSES: License[] = [
  {
    id: 'lic-1',
    subscriptionId: 'sub-1',
    companyId: 'comp-1',
    deviceTypeId: 'dt-1',
    key: 'LIC-7721-9902-8812-4451',
    status: 'Active',
    workflowStatus: LicenseStatusEnum.ACTIVE,
    activationStatus: ActivationStatusEnum.ACTIVATED,
    expiryDate: '2026-01-01',
    activationsCount: 45,
    maxActivations: 1,
  },
  {
    id: 'lic-2',
    subscriptionId: 'sub-2',
    companyId: 'comp-2',
    deviceTypeId: 'dt-1',
    key: 'LIC-PENDING-0000',
    status: 'Revoked',
    workflowStatus: LicenseStatusEnum.REVOKED,
    activationStatus: ActivationStatusEnum.BLOCKED,
    expiryDate: '2025-04-15',
    activationsCount: 0,
    maxActivations: 1,
  },
  {
    id: 'lic-3',
    subscriptionId: 'sub-3',
    companyId: 'comp-3',
    deviceTypeId: 'dt-1',
    key: 'LIC-1122-3344-5566-7788',
    status: 'Expired',
    workflowStatus: LicenseStatusEnum.EXPIRED,
    activationStatus: ActivationStatusEnum.ACTIVATED,
    expiryDate: '2024-12-01',
    activationsCount: 1,
    maxActivations: 1,
  },
];

export const MOCK_OFFLINE_LICENSES: OfflineLicenseRecord[] = [
  {
    id: 'off-1',
    companyId: 'comp-1',
    subscriptionId: 'sub-1',
    planId: 'plan-3',
    productType: 'Digital Signage',
    deviceTypeId: 'dt-1',
    seats: 10,
    status: 'Awaiting Fingerprint',
    workflowStatus: LicenseStatusEnum.ACTIVATION_PENDING,
    activationStatus: ActivationStatusEnum.NOT_BOUND,
    genericLicenseFileName: 'TechCorp_M-0003_generic.lic',
    notes: 'Generic offline license has been emailed to customer.',
    createdAt: '2026-03-12',
    approvedAt: '2026-03-12',
    issuedAt: '2026-03-12',
  },
  {
    id: 'off-2',
    companyId: 'comp-2',
    subscriptionId: 'sub-2',
    planId: 'plan-2',
    productType: 'Digital Signage',
    deviceTypeId: 'dt-1',
    seats: 5,
    status: 'Fingerprint Uploaded',
    workflowStatus: LicenseStatusEnum.ACTIVATION_PENDING,
    activationStatus: ActivationStatusEnum.REQUEST_RECEIVED,
    genericLicenseFileName: 'GlobalFinance_M-0002_generic.lic',
    requestFileName: 'GlobalFinance_branch-01.req',
    fingerprintHash: 'FP-9A21F8D0B144',
    notes: 'Awaiting admin bind-and-activate action.',
    createdAt: '2026-03-10',
    approvedAt: '2026-03-10',
    issuedAt: '2026-03-10',
  },
  {
    id: 'off-3',
    companyId: 'comp-1',
    subscriptionId: 'sub-1',
    planId: 'plan-4',
    productType: 'Digital Signage',
    deviceTypeId: 'dt-2',
    seats: 25,
    status: 'Activated',
    workflowStatus: LicenseStatusEnum.ACTIVE,
    activationStatus: ActivationStatusEnum.ACTIVATED,
    genericLicenseFileName: 'TechCorp_M-0004_generic.lic',
    finalLicenseFileName: 'TechCorp_signage-linux_final.lic',
    requestFileName: 'TechCorp_signage-linux.req',
    fingerprintHash: 'FP-44C19A81E210',
    notes: 'Activated and delivered to customer on 2026-03-08.',
    createdAt: '2026-03-06',
    approvedAt: '2026-03-06',
    issuedAt: '2026-03-06',
    activatedAt: '2026-03-08',
  },
];

export const MOCK_OFFLINE_REQUESTS: OfflineActivationRequest[] = [
  {
    id: 'off-req-1',
    offlineLicenseId: 'off-2',
    requestFileName: 'GlobalFinance_branch-01.req',
    fingerprintHash: 'FP-9A21F8D0B144',
    fingerprint: {
      machineName: 'GF-BRANCH-01',
      macAddress: '00:1A:2B:3C:4D:5E',
      ipAddress: '10.0.1.24',
      hostName: 'branch-kiosk-01',
      osHash: 'OS-89A7220F',
    },
    uploadedAt: '2026-03-14',
    status: 'Uploaded',
    activationStatus: ActivationStatusEnum.REQUEST_RECEIVED,
  },
  {
    id: 'off-req-2',
    offlineLicenseId: 'off-3',
    requestFileName: 'TechCorp_signage-linux.req',
    fingerprintHash: 'FP-44C19A81E210',
    fingerprint: {
      machineName: 'TC-LNX-SIGNAGE-02',
      macAddress: '00:AA:4C:00:22:31',
      ipAddress: '172.16.0.44',
      hostName: 'signage-node-02',
      osHash: 'OS-2D8831AF',
    },
    uploadedAt: '2026-03-08',
    status: 'Processed',
    activationStatus: ActivationStatusEnum.ACTIVATED,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Admin User',
    email: 'admin@licmanager.com',
    role: 'Super Admin',
    designation: 'System Architect',
    mobile: '+1 555-9000',
    lastLogin: '2025-03-19 10:30',
    theme: 'light',
    menuPosition: 'sidebar',
    profilePhoto: 'https://picsum.photos/seed/admin/200',
  },
  {
    id: 'user-2',
    name: 'License Manager',
    email: 'manager@licmanager.com',
    role: 'License Admin',
    designation: 'Operations Manager',
    mobile: '+1 555-9001',
    lastLogin: '2025-03-19 09:15',
    theme: 'light',
    menuPosition: 'sidebar',
    profilePhoto: 'https://picsum.photos/seed/manager/200',
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: 'log-1',
    userId: 'user-1',
    action: 'Plan Created',
    resource: 'Enterprise Pro',
    timestamp: '2025-03-19 10:45',
    status: 'Success',
  },
  {
    id: 'log-2',
    userId: 'user-2',
    action: 'Subscription Approved',
    resource: 'TechCorp Solutions',
    timestamp: '2025-03-19 10:30',
    status: 'Success',
  },
  {
    id: 'log-3',
    userId: 'user-1',
    action: 'License Revoked',
    resource: 'Global Finance Inc',
    timestamp: '2025-03-19 09:00',
    status: 'Success',
  },
];

export const DEFAULT_CONFIG: ConfigSettings = {
  licensePolicy: {
    gracePeriod: 7,
    allowOveruse: true,
    overuseThreshold: 10,
  },
  jwtConfig: {
    issuer: 'lic-manager-server',
    expiry: 3600,
    algorithm: 'RS256',
  },
  encryption: {
    keySize: 2048,
    method: 'AES-256-GCM',
  },
};
